# Generated by Django 5.1.1 on 2024-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('meal_description', models.TextField()),
                ('image', models.URLField()),
                ('protein_content', models.FloatField()),
                ('ingredients', models.JSONField()),
                ('recipe_instructions', models.JSONField()),
                ('recipe_serving_size', models.IntegerField()),
                ('keywords', models.JSONField()),
                ('recipe_category', models.CharField(max_length=255)),
            ],
        ),
    ]
