# Generated by Django 5.1.1 on 2024-11-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcosapp', '0002_alter_recipe_author_name_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_serving_size',
        ),
    ]
